### ISSUE TITLE
Hacktoberfest 2020

### ISSUE THREAD

**Issue by theashwin** [theashwin/competitive-programming#5]
Hey,

I am opening this repository for you guys to participate in hacktoberfest 2020, this can be your first step into the world of competitive programming. You can contribute solutions in the following languages.

- C++
- C
- Python
- Java

Other instructions are in CONTRIBUTING.md

Thanks,
AP

**Comment by yash3001** [comment]
Where is CONTRIBUTING.md?

**Comment by theashwin** [comment]
https://github.com/theashwin/competitive-programming/blob/master/CONTRIBUTING.md

**Comment by kashc11** [comment]
Hi! I'd like to contribute, can you assign it to me?

**Comment by Sindhu-321** [comment]
I would like to contribute to the issue.
May I get assigned?

**Comment by forntoh** [comment]
I'd love to contribute

**Comment by theashwin** [comment]
Just create a new issue and describe the problem you want to contribute, I'll assign it to you.
